### ISSUE TITLE
Iranian bank accounts sheba number regex

### ISSUE THREAD

**Issue by 1mehdifaraji** [majidh1/regex-list#18]
Please provide a regex for bank accounts `IR` sheba number. The regex that I wanted to use was 
```
const shebaRegex = /{2}[0-9]{24}/
``` 
but it's invalid.

**Comment by majidh1** [comment]
To create a valid regex for Iranian Sheba numbers (IBAN), which have the format "IR" followed by 24 digits, you can use the following regex pattern:

```js
const shebaRegex = /^IR[0-9]{24}$/;
```
